export const languageMap = {
  'en': 'English',
  'hi': 'Hindi',
  'es': 'Spanish',
  'fr': 'French',
  'de': 'German',
  'it': 'Italian',
  'pt': 'Portuguese',
  'ru': 'Russian',
  'ja': 'Japanese',
  'ko': 'Korean',
  'zh': 'Chinese',
  'ar': 'Arabic',
  'tr': 'Turkish',
  'pl': 'Polish',
  'nl': 'Dutch',
  'sv': 'Swedish',
  'no': 'Norwegian',
  'da': 'Danish',
  'fi': 'Finnish',
  'cs': 'Czech',
  'hu': 'Hungarian',
  'ro': 'Romanian',
  'bg': 'Bulgarian',
  'hr': 'Croatian',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'et': 'Estonian',
  'lv': 'Latvian',
  'lt': 'Lithuanian',
  'el': 'Greek',
  'he': 'Hebrew',
  'th': 'Thai',
  'vi': 'Vietnamese',
  'id': 'Indonesian',
  'ms': 'Malay',
  'tl': 'Filipino',
  'sw': 'Swahili',
  'zu': 'Zulu',
  'af': 'Afrikaans',
  'am': 'Amharic',
  'az': 'Azerbaijani',
  'be': 'Belarusian',
  'bn': 'Bengali',
  'bs': 'Bosnian',
  'ca': 'Catalan',
  'cy': 'Welsh',
  'eo': 'Esperanto',
  'eu': 'Basque',
  'fa': 'Persian',
  'ga': 'Irish',
  'gd': 'Scottish Gaelic',
  'gl': 'Galician',
  'gu': 'Gujarati',
  'ha': 'Hausa',
  'hy': 'Armenian',
  'ig': 'Igbo',
  'is': 'Icelandic',
  'jv': 'Javanese',
  'ka': 'Georgian',
  'kk': 'Kazakh',
  'km': 'Khmer',
  'kn': 'Kannada',
  'ku': 'Kurdish',
  'ky': 'Kyrgyz',
  'la': 'Latin',
  'lb': 'Luxembourgish',
  'lo': 'Lao',
  'mk': 'Macedonian',
  'ml': 'Malayalam',
  'mn': 'Mongolian',
  'mr': 'Marathi',
  'mt': 'Maltese',
  'my': 'Myanmar',
  'ne': 'Nepali',
  'or': 'Odia',
  'pa': 'Punjabi',
  'ps': 'Pashto',
  'sd': 'Sindhi',
  'si': 'Sinhala',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'ta': 'Tamil',
  'te': 'Telugu',
  'tg': 'Tajik',
  'tk': 'Turkmen',
  'tt': 'Tatar',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'uz': 'Uzbek',
  'xh': 'Xhosa',
  'yi': 'Yiddish',
  'yo': 'Yoruba',
  'sa': 'Sanskrit',
  'as': 'Assamese',
  'ks': 'Kashmiri',
  'dv': 'Dhivehi',
  'bo': 'Tibetan',
  'ug': 'Uyghur',
  'me': 'Montenegrin',

  // Language variants
  'zh-cn': 'Chinese (Simplified)',
  'zh-tw': 'Chinese (Traditional)',
  'zh-hk': 'Chinese (Hong Kong)',
  'pt-br': 'Portuguese (Brazil)',
  'pt-pt': 'Portuguese (Portugal)',
  'es-es': 'Spanish (Spain)',
  'es-mx': 'Spanish (Mexico)',
  'es-ar': 'Spanish (Argentina)',
  'en-us': 'English (US)',
  'en-gb': 'English (UK)',
  'en-ca': 'English (Canada)',
  'en-au': 'English (Australia)',
  'fr-fr': 'French (France)',
  'fr-ca': 'French (Canada)',
  'de-de': 'German (Germany)',
  'de-at': 'German (Austria)',
  'de-ch': 'German (Switzerland)',
  'ar-sa': 'Arabic (Saudi Arabia)',
  'ar-eg': 'Arabic (Egypt)',
  'ar-ae': 'Arabic (UAE)'
}as const;

export type LanguageMap = typeof languageMap;
export type LanguageCode = keyof LanguageMap;

export  function convertLanguageCode(langCode:string) {  
  const lowerCaseCode = langCode.toLowerCase();

  if (lowerCaseCode in languageMap) {
    return languageMap[lowerCaseCode as LanguageCode];
  }

  const baseCode = lowerCaseCode.split('-')[0];
  if (baseCode in languageMap) {
    return languageMap[baseCode as LanguageCode];
  }

  return 'Unknown';
}

export function getAllLanguageNames(languages:LanguageMap) {  
  return Object.values(languages);
}